#!/bin/bash
#cd /home/myuser/CASE
#DATA_PATH_DOCKER=${1:-}
#file_name=${2:-15.xyz}


echo ${SINGULARITYID}; #export DISPLAY=:1;
glxgears > ~/.vnc/out_glxgears 2>&1 &
PID=$!
echo glxgears $PID
#/dev/null 2>&1 &

i=0
while [ true ]; do
    sleep 1
    ps -a |grep $PID
    #glxgears | wc -l |awk '{print ($1 >= 1)}' |grep 1
    RET=$?
    if [ $RET -eq 0 ]; then
	break
    elif [ $i -gt 100 ]; then
	break
    fi
    i=$((i+1))
done
exit $RET
#strings /proc/1759194/environ |grep DISPLAY
# ps -a |grep  1759576
